apiVersion: 1

datasources:
  - uid: ef3hhd5crjv9ce
    name: prometheus
    type: prometheus
    typeName: Prometheus
    typeLogoUrl: public/plugins/prometheus/img/prometheus_logo.svg
    access: proxy
    url: http://host.docker.internal:9090/
    user: ''
    database: ''
    basicAuth: false
    isDefault: true
    jsonData:
      pdcInjected: false
    readOnly: false
